export CASE_SEPARATORS          = new RegExp "([A-Z])|[_\\-\\.]", "g"
export CASE_WHITESPACE          = new RegExp "\\s+", "g"
export COFFEE_EXTENSION         = new RegExp "\\.(coffee|litcoffee|coffee\\.md)$", "i"
export COMMON_JS_CONTENT        = new RegExp "exports[\\[\\.( ?=)]|module\\.exports|require\\(|createRequire\\(", "i"
export PATTERN_PLACEHOLDERS     = new RegExp "(?<pattern>\\{\\{\\s*(?<placeholder>[a-z0-9-_\\.]+?)\\s*\\}\\})", "gmi"
export PLACEHOLDERS             = new RegExp "\\{\\{\\s*(?<placeholder>[a-z0-9-_\\.]+?)\\s*\\}\\}", "gmi"
export STARTS_WITH_BASE_PATH    = new RegExp "^([~|@]/)"
export STARTS_WITH_PACKAGE_PATH = new RegExp "^~\\/"
export STARTS_WITH_PROJECT_PATH = new RegExp "^@\\/"
export YAML_EXTENSION           = new RegExp "\\.ya?ml$", "i"
