ruby:
  version: "3.3.0"

linting:
  enabled: true
  linters:
    - rubocop

formatting:
  enabled: true
  formatters:
    - rubocop

completion:
  enabled: true

include:
  - "Gemfile"
  - "tools/slim/**/*.rb"

# debugging:
#   enabled: true
