version: "3"

tasks:
  prettier-ignore-generate:
    desc: "Generate .prettierignore file combining .gitignore and existing .prettierignore"
    internal: true
    cmd: |
      cat \
        {{.PLATE_PKG_PATH}}/.gitignore \
        {{.PLATE_PKG_PATH}}/configs/.prettierignore \
        > {{.PLATE_PKG_PATH}}/tmp/.prettierignore

  prettier:
    desc: "Run Prettier with specified action (check or write)"
    internal: true
    requires:
      vars: [ACTION]
    cmds:
      - task: prettier-ignore-generate
      - |
        {{.PLATE_BIN_PATH}}/prettier \
          --{{.ACTION}} \
          --config {{.PLATE_PKG_PATH}}/configs/prettierrc.yml \
          --ignore-path {{.PLATE_PKG_PATH}}/tmp/.prettierignore \
          "{{.PLATE_PKG_PATH}}/**/*.{feature,md,yml}"

  format:
    desc: "Check formatting"
    ignore_error: true
    cmd:
      task: prettier
      vars:
        ACTION: check

  format-fix:
    desc: "Fix formatting"
    ignore_error: true
    cmd:
      task: prettier
      vars:
        ACTION: write

  lint:
    desc: "Check linting for CoffeeScript files"
    ignore_error: true
    cmds:
      - task: :utilities:yaml-to-json
        vars:
          SOURCE: configs/coffeelint.yml
          TARGET: tmp/coffeelint.json

      - |
        coffeelint_files=$(find {{.PLATE_PKG_PATH}}/{library,tests} -name "*.coffee" -type f)

        {{.PLATE_BIN_PATH}}/coffeelint \
          --file ./tmp/coffeelint.json \
          $coffeelint_files
