version: "3"

tasks:
  clean:
    desc: "Clean up the project"
    cmds:
      - rm -rvf {{.PLATE_PRJ_PATH}}/src

  build:
    desc: "Build the project from CoffeeScript sources"
    sources:
      - "{{.PLATE_PRJ_PATH}}/lib/**/*.coffee"
    generates:
      - "{{.PLATE_PRJ_PATH}}/src/**/*.js"
    cmds:
      - |
        {{.PLATE_BIN_PATH}}/coffee \
          --bare \
          --compile \
          --no-header \
          --output {{.PLATE_PRJ_PATH}}/src \
          {{.PLATE_PRJ_PATH}}/lib

  clean-cli:
    desc: "Clean up the project"
    cmds:
      - rm -rvf {{.PLATE_PRJ_PATH}}/bin/plate.js

  build-cli:
    desc: "Build the CoffeeScript CLI bootstrap"
    sources:
      - "{{.PLATE_PKG_PATH}}/bin/plate.coffee"
    generates:
      - "{{.PLATE_PKG_PATH}}/bin/plate.js"
    cmds:
      - |
        {{.PLATE_BIN_PATH}}/coffee \
          --bare \
          --compile \
          --no-header \
          {{.PLATE_PKG_PATH}}/bin/plate.coffee

  watch:
    desc: "Watch the project for changes and rebuild"
    cmds:
      - |
        {{.PLATE_BIN_PATH}}/coffee \
          --bare \
          --compile \
          --inline-map \
          --no-header \
          --watch \
          --output {{.PLATE_PRJ_PATH}}/src \
          {{.PLATE_PRJ_PATH}}/lib

  build-test:
    desc: "Build test files from CoffeeScript sources"
    deps: [build]
    sources:
      - "{{.PLATE_PRJ_PATH}}/tests/**/*.coffee"
    generates:
      - "{{.PLATE_PRJ_PATH}}/src/tests/**/*.js"
    cmds:
      - |
        {{.PLATE_BIN_PATH}}/coffee \
          --bare \
          --compile \
          --no-header \
          --output {{.PLATE_PRJ_PATH}}/src/tests \
          {{.PLATE_PRJ_PATH}}/tests

  test:
    desc: "Run Cucumber tests"
    deps: [build-test]
    sources:
      - "{{.PLATE_PRJ_PATH}}/src/tests/**/*.js"
      - "{{.PLATE_PRJ_PATH}}/tests/**/*.feature"
      - "{{.PLATE_CONF_PATH}}/cucumber.yml"
    generates:
      - "{{.PLATE_TMP_PATH}}/cucumber-report.html"
    cmds:
      - |
        echo "=== DEBUGGING CUCUMBER SETUP ==="
        echo "Current working directory: $(pwd)"
        echo "PLATE_PRJ_PATH: {{.PLATE_PRJ_PATH}}"
        echo "PLATE_PKG_PATH: {{.PLATE_PKG_PATH}}"
        echo ""
        
        # Create temp directory
        mkdir -p "{{.PLATE_TMP_PATH}}"
        
        # Check if files exist
        echo "=== CHECKING FILE EXISTENCE ==="
        echo "Feature files:"
        find "{{.PLATE_PRJ_PATH}}/tests" -name "*.feature" -type f || echo "No feature files found"
        echo ""
        echo "Support files:"
        find "{{.PLATE_PRJ_PATH}}/src/tests/support" -name "*.js" -type f 2>/dev/null || echo "No support files found"
        echo ""
        echo "Step files:"
        find "{{.PLATE_PRJ_PATH}}/src/tests/steps" -name "*.js" -type f 2>/dev/null || echo "No step files found"
        echo ""
        
        # Process config
        cucumber_yml_tmp="{{.PLATE_TMP_PATH}}/cucumber.yml"
        
        echo "=== PROCESSING CONFIG ==="
        echo "Original config:"
        cat "{{.PLATE_CONF_PATH}}/cucumber.yml"
        echo ""
        
        # Process the cucumber config with absolute paths
        yq eval --yaml-fix-merge-anchor-to-spec -o=json '.' "{{.PLATE_CONF_PATH}}/cucumber.yml" | \
        yq eval '.default.paths = ["{{.PLATE_PRJ_PATH}}/tests/features/**/*.feature"] | 
                 .default.import = ["{{.PLATE_PRJ_PATH}}/src/tests/support/**/*.js", "{{.PLATE_PRJ_PATH}}/src/tests/steps/**/*.js"] | 
                 .debug.paths = ["{{.PLATE_PRJ_PATH}}/tests/features/**/*.feature"] | 
                 .debug.import = ["{{.PLATE_PRJ_PATH}}/src/tests/support/**/*.js", "{{.PLATE_PRJ_PATH}}/src/tests/steps/**/*.js"]' - | \
        yq eval -P '.' - > "$cucumber_yml_tmp"
        
        echo "Processed config:"
        cat "$cucumber_yml_tmp"
        echo ""
        
        # Test if cucumber can find the config
        if [ ! -f "$cucumber_yml_tmp" ]; then
          echo "ERROR: Config file not created!"
          exit 1
        fi
        
        echo "=== RUNNING CUCUMBER ==="
        cd "{{.PLATE_PRJ_PATH}}"
        
        # Run with full debugging
        "{{.PLATE_BIN_PATH}}/cucumber-js" \
          --config="$cucumber_yml_tmp" \
          {{.CLI_ARGS}} || echo "Dry run failed"
        
        echo ""
        echo "=== RUNNING CUCUMBER FOR REAL ==="
        "{{.PLATE_BIN_PATH}}/cucumber-js" \
          --config="$cucumber_yml_tmp" \
          {{.CLI_ARGS}}
        
        # Cleanup
        rm -f "$cucumber_yml_tmp"


        rm -frv "$cucumber_yml_tmp"

  test-report:
    desc: "Open test report in browser"
    deps: [test]
    cmds:
      - open "file://{{.PLATE_PKG_PATH}}/tmp/cucumber-report.html"

  run:
    desc: "Run the project via Node.js"
    deps: [build]
    cmds:
      - |
        node \
          --trace-warnings \
          --trace-deprecation \
          --trace-uncaught \
          --import="{{.PLATE_PKG_PATH}}/src/registry.js" {{.CLI_ARGS}}
