version: "3"

tasks:
  format:
    desc: "Check formatting for coffee, css, scss files"
    sources:
      - "{{.PLATE_PRJ_PATH}}/**/*.coffee"
      - "{{.PLATE_CONF_PATH}}/prettierrc.yml"
      - "{{.PLATE_CONF_PATH}}/.prettierignore"
    method: checksum
    cmds:
      - |
        {{.PLATE_BIN_PATH}}/prettier \
          --check \
          --config {{.PLATE_CONF_PATH}}/prettierrc.yml \
          --ignore-path {{.PLATE_CONF_PATH}}/.prettierignore \
          "{{.PLATE_PRJ_PATH}}/**/*.coffee"

  format-fix:
    desc: "Automatically fix formatting issues in supported files"
    sources:
      - "{{.PLATE_PRJ_PATH}}/**/*.coffee"
      - "{{.PLATE_CONF_PATH}}/prettierrc.yml"
      - "{{.PLATE_CONF_PATH}}/.prettierignore"
    generates:
      - "{{.PLATE_PRJ_PATH}}/**/*.coffee"
    cmds:
      - |
        {{.PLATE_BIN_PATH}}/prettier \
          --write \
          --config {{.PLATE_CONF_PATH}}/prettierrc.yml \
          --ignore-path {{.PLATE_PKG_PATH}}/.prettierignore \
          "{{.PLATE_PRJ_PATH}}/**/*.coffee"

  lint:
    desc: "Check linting for CoffeeScript files"
    sources:
      - "{{.PLATE_PRJ_PATH}}/{source,lib,tests}/**/*.coffee"
      - "{{.PLATE_CONF_PATH}}/coffeelint.yml"
    generates:
      - "{{.PLATE_TMP_PATH}}/coffeelint.json"
    method: checksum
    cmds:
      - |
        set --local coffeelint_json_tmp {{.PLATE_TMP_PATH}}/coffeelint.json
        set --local coffeelint_files (find {{.PLATE_PRJ_PATH}}/{source,lib,tests} -name "*.coffee" -type f)

        yq -o=json {{.PLATE_CONF_PATH}}/coffeelint.yml > $coffeelint_json_tmp

        {{.PLATE_BIN_PATH}}/coffeelint \
          --file $coffeelint_json_tmp \
          $coffeelint_files

  all:
    desc: "Run all code quality checks"
    deps: [format, lint]
    cmds:
      - echo "All code quality checks completed successfully"
