version: "3"

vars:
  PLATE_ENV: '{{.ENV.PLATE_ENV | default "development"}}'
  PLATE_PKG_PATH: "{{.ENV.PLATE_PKG_PATH | default .USER_WORKING_DIR}}"

dir: "{{.PLATE_PKG_PATH}}"

includes:
  build:
    dir: "{{.PLATE_PKG_PATH}}"
    optional: false
    taskfile: ./Taskfile.build.yml
  tests:
    dir: "{{.PLATE_PKG_PATH}}"
    optional: false
    taskfile: ./Taskfile.tests.yml
  quality:
    dir: "{{.PLATE_PKG_PATH}}"
    optional: false
    taskfile: ./Taskfile.quality.yml
  utilities:
    dir: "{{.PLATE_PKG_PATH}}"
    optional: false
    taskfile: ./Taskfile.utilities.yml

tasks:
  default:
    desc: "Show available tasks across all namespaces"
    cmd: task --list-all

  environment:
    desc: "Display environment variables"
    cmds:
      - |
        echo "PLATE Environment Variables"
        echo "=========================="
        echo "PLATE_ENV: {{.PLATE_ENV}}"
        echo "PLATE_PKG_PATH: {{.PLATE_PKG_PATH}}"
