version: "3"

tasks:
  run:
    desc: "Run Cucumber tests"
    cmds:
      - pnpm run test

  report:
    desc: "Open test report in browser"
    cmds:
      - task: run
        vars:
          CLI_ARGS: "{{.CLI_ARGS}}"

      - defer: open "file://{{.PLATE_PKG_PATH}}/tmp/cucumber-report.html"

  prototypes:
    desc: "Run all patterns in parallel"
    deps:
      - task: run
        env:
          TEST_PATTERN: functional
      - task: run
        env:
          TEST_PATTERN: class
      - task: run
        env:
          TEST_PATTERN: prototype
