version: "3"

tasks:
  prettier:
    desc: "Run Prettier with specified action (check or write)"
    internal: true
    requires:
      vars: [ACTION]
    cmd: |
      {{.PLATE_PKG_PATH}}/node_modules/.bin/prettier \
        --{{.ACTION}} \
        --config {{.PLATE_PKG_PATH}}/configs/prettierrc.yml \
        --ignore-path {{.PLATE_PKG_PATH}}/configs/.prettierignore \
        "{{.PLATE_PKG_PATH}}/**/*.{feature,md,yml}"

  format:
    desc: "Check formatting"
    ignore_error: true
    cmd:
      task: prettier
      vars:
        ACTION: check

  format-fix:
    desc: "Fix formatting"
    ignore_error: true
    cmd:
      task: prettier
      vars:
        ACTION: write

  lint:
    desc: "Check linting for CoffeeScript files"
    ignore_error: true
    cmds:
      - task: :utilities:yaml-to-json
        vars:
          SOURCE: configs/coffeelint.yml
          TARGET: tmp/coffeelint.json

      - |
        coffeelint_files=$(find {{.PLATE_PKG_PATH}}/{library,tests} -name "*.coffee" -type f)

        {{.PLATE_PKG_PATH}}/node_modules/.bin/coffeelint \
          --file ./tmp/coffeelint.json \
          $coffeelint_files
