version: "3"

tasks:
  clean:
    desc: "Clean up the project"
    cmds:
      - rm -rvf {{.PLATE_PRJ_PATH}}/src

  build:
    desc: "Build the project from CoffeeScript sources"
    sources:
      - "{{.PLATE_PRJ_PATH}}/lib/**/*.coffee"
    generates:
      - "{{.PLATE_PRJ_PATH}}/src/**/*.js"
    cmds:
      - |
        {{.PLATE_BIN_PATH}}/coffee \
          --bare \
          --compile \
          --no-header \
          --output {{.PLATE_PRJ_PATH}}/src \
          {{.PLATE_PRJ_PATH}}/lib

  clean-cli:
    desc: "Clean up the project"
    cmds:
      - rm -rvf {{.PLATE_PRJ_PATH}}/bin/plate.js

  build-cli:
    desc: "Build the CoffeeScript CLI bootstrap"
    sources:
      - "{{.PLATE_PKG_PATH}}/bin/plate.coffee"
    generates:
      - "{{.PLATE_PKG_PATH}}/bin/plate.js"
    cmds:
      - |
        {{.PLATE_BIN_PATH}}/coffee \
          --bare \
          --compile \
          --no-header \
          {{.PLATE_PKG_PATH}}/bin/plate.coffee

  watch:
    desc: "Watch the project for changes and rebuild"
    cmds:
      - |
        {{.PLATE_BIN_PATH}}/coffee \
          --bare \
          --compile \
          --inline-map \
          --no-header \
          --watch \
          --output {{.PLATE_PRJ_PATH}}/src \
          {{.PLATE_PRJ_PATH}}/lib

  build-test:
    desc: "Build test files from CoffeeScript sources"
    deps: [build]
    sources:
      - "{{.PLATE_PRJ_PATH}}/tests/**/*.coffee"
    generates:
      - "{{.PLATE_PRJ_PATH}}/src/tests/**/*.js"
    cmds:
      - |
        {{.PLATE_BIN_PATH}}/coffee \
          --bare \
          --compile \
          --no-header \
          --output {{.PLATE_PRJ_PATH}}/src/tests \
          {{.PLATE_PRJ_PATH}}/tests

  test:
    desc: "Run Cucumber tests"
    deps: [build-test]
    sources:
      - "{{.PLATE_PRJ_PATH}}/src/tests/**/*.js"
      - "{{.PLATE_PRJ_PATH}}/tests/**/*.feature"
      - "{{.PLATE_CONF_PATH}}/cucumber.yml"
    generates:
      - "{{.PLATE_TMP_PATH}}/cucumber-report.html"
    cmds:
      - |
        cucumber_yml_tmp="{{.PLATE_TMP_PATH}}/cucumber.yml"
        cucumber_yml_tmp_relative="../tmp/cucumber.yml"
        mkdir -p "{{.PLATE_TMP_PATH}}"

        yq eval --yaml-fix-merge-anchor-to-spec -o=json '.' {{.PLATE_CONF_PATH}}/cucumber.yml | \
        yq eval -P '.' - > "$cucumber_yml_tmp"

        {{.PLATE_BIN_PATH}}/cucumber-js \
          --config="$cucumber_yml_tmp_relative" {{.CLI_ARGS}}

        rm -frv "$cucumber_yml_tmp"

  test-report:
    desc: "Open test report in browser"
    deps: [test]
    cmds:
      - open "file://{{.PLATE_PKG_PATH}}/tmp/cucumber-report.html"

  run:
    desc: "Run the project via Node.js"
    deps: [build]
    cmds:
      - |
        node \
          --trace-warnings \
          --trace-deprecation \
          --trace-uncaught \
          --import="{{.PLATE_PKG_PATH}}/src/registry.js" {{.CLI_ARGS}}
