version: "3"

tasks:
  clean:
    desc: "Clean up the project"
    cmds:
      - rm -rvf {{.PLATE_PRJ_PATH}}/src/tests

  build:
    desc: "Build test files from CoffeeScript sources"
    deps: [dev:build]
    sources:
      - "{{.PLATE_PRJ_PATH}}/tests/**/*.coffee"
    generates:
      - "{{.PLATE_PRJ_PATH}}/src/tests/**/*.js"
    cmds:
      - task transpile:build tests

  run:
    desc: "Run Cucumber tests"
    deps: [build]
    cmds:
      - |
        mkdir -p "{{.PLATE_TMP_PATH}}"

        cucumber_yml_relative_path="tmp/cucumber.yml"
        cucumber_yml_absolute_path="{{.PLATE_TMP_PATH}}/cucumber.yml"

        yq eval --yaml-fix-merge-anchor-to-spec -o=json '.' {{.PLATE_CONF_PATH}}/cucumber.yml | \
        yq eval -P '.' - > "$cucumber_yml_absolute_path"

        {{.PLATE_BIN_PATH}}/cucumber-js \
          --config="$cucumber_yml_relative_path" {{.CLI_ARGS}}

        rm -frv "$cucumber_yml_absolute_path"

  report:
    desc: "Open test report in browser"
    cmds:
      - cmd: task test:run {{.CLI_ARGS}}
        ignore_error: true
      - open "file://{{.PLATE_TMP_PATH}}/cucumber-report.html"
