version: "3"

tasks:
  compile:
    desc: "Compile CoffeeScript to JavaScript (output to tmp)"
    requires:
      vars: [TARGET]
    vars:
      TARGET: '{{.TARGET | default "library"}}'
    cmds:
      - |
        {{.PLATE_BIN_PATH}}/coffee \
          --bare \
          --compile \
          --map \
          --no-header \
          --output {{.PLATE_PKG_PATH}}/tmp/{{.TARGET}} \
          {{.PLATE_PKG_PATH}}/{{.TARGET}}

  transform:
    desc: "Transform JavaScript with Babel (tmp to src)"
    requires:
      vars: [TARGET]
    cmds:
      - |
        task :yaml-to-json \
          SOURCE=configs/babel.yml \
          TARGET=tmp/.babelrc

      - |
        {{.PLATE_BIN_PATH}}/babel \
          {{.PLATE_PKG_PATH}}/tmp/{{.TARGET}} \
          --config-file {{.PLATE_PKG_PATH}}/tmp/.babelrc \
          --out-dir {{.PLATE_PKG_PATH}}/src/{{.TARGET}} \
          --source-maps

      - task :clean TARGET=tmp/.babelrc

  run:
    desc: "Execute full transpilation pipeline (compile + transform)"
    requires:
      vars: [TARGET]
    cmds:
      - task compile TARGET='{{.TARGET}}'
      - task transform TARGET='{{.TARGET}}'