version: "3"

tasks:
  clean:
    desc: "Clean up the project"
    cmds:
      - rm -rvf {{.PLATE_PRJ_PATH}}/src

  build:
    desc: "Build the project from CoffeeScript sources"
    sources:
      - "{{.PLATE_PRJ_PATH}}/library/**/*.coffee"
      - "{{.PLATE_PRJ_PATH}}/runtime/**/*.coffee"
    generates:
      - "{{.PLATE_PRJ_PATH}}/src/library/**/*.js"
      - "{{.PLATE_PRJ_PATH}}/src/runtime/**/*.js"
    cmds:
      - |
        {{.PLATE_BIN_PATH}}/coffee \
          --bare \
          --compile \
          --map \
          --no-header \
          --output {{.PLATE_PKG_PATH}}/src \
          --transpile \
          {{.PLATE_PKG_PATH}}/library \
          {{.PLATE_PKG_PATH}}/runtime

  run:
    desc: "Run the project via Node.js"
    deps: [build]
    cmds:
      - |
        node \
          --trace-deprecation \
          --trace-uncaught \
          --trace-warnings \
          --import="{{.PLATE_PKG_PATH}}/src/registry.js" \
          {{.CLI_ARGS}}
