server:
  hostname: localhost
  ip: 0.0.0.0
  path: /
  port: 1234

globs:
  clean: tmp/**/*

  assets:
    src: assets/**/*
    dest: tmp/assets

  scripts:
    src: scripts/**/*.coffee
    dest: tmp/scripts
