coffeescript_error:
  level: error

arrow_spacing:
  level: error

braces_spacing:
  level: error
  spaces: 1

bracket_spacing:
  level: error
  spaces: 0
  empty_array_spaces: 0

camel_case_classes:
  level: error

colon_assignment_spacing:
  level: error
  spacing:
    left: 0
    right: 1

cyclomatic_complexity:
  level: error
  value: 10

duplicate_key:
  level: error

empty_constructor_needs_parens:
  level: error

ensure_comprehensions:
  level: error

eol_last:
  level: error

indentation:
  level: error
  value: 2

line_endings:
  level: error
  value: unix

max_line_length:
  level: error
  limitComments: false
  value: 120

missing_fat_arrows:
  level: ignore
  is_strict: false

missing_parseint_radix:
  level: error

newlines_after_classes:
  level: error
  value: 1

no_backticks:
  level: error

no_debugger:
  level: error

no_empty_functions:
  level: error

no_empty_param_list:
  level: error

no_implicit_braces:
  level: error
  strict: true

no_implicit_parens:
  level: ignore
  strict: false

no_interpolation_in_single_quotes:
  level: error

no_nested_string_interpolation:
  level: error

no_plusplus:
  level: error

no_private_function_fat_arrows:
  level: error

no_spaces:
  level: ignore

no_stand_alone_at:
  level: ignore
# https: //github.com/jashkenas/coffee-script/issues/1601

no_tabs:
  level: error

no_this:
  level: error

no_throwing_strings:
  level: error

no_trailing_semicolons:
  level: error

no_trailing_whitespace:
  level: error

no_unnecessary_double_quotes:
  level: ignore

no_unnecessary_fat_arrows:
  level: error

non_empty_constructor_needs_parens:
  level: ignore

object_shorthand:
  level: ignore

prefer_english_operator:
  level: error

prefer_fat_arrows_in_methods:
  level: ignore

prefer_logical_operator:
  level: ignore

space_operators:
  level: error

spacing_after_comma:
  level: error
  ignore_elision: false

transform_messes_up_line_numbers:
  level: error
