default: &default
  failFast: false
  forceExit: true
  language: en
  parallel: 4
  retry: 1
  verbose: false

  paths:
    - tests/features/**/*.feature

  import:
    - src/tests/support/**/*.js
    - src/tests/steps/**/*.js

  format:
    - "pretty"
    - "html:tmp/cucumber-report.html"

  formatOptions:
    colorsEnabled: true
    printAttachments: true

debug:
  <<: *default

  failFast: true
  parallel: 1
  verbose: true
