default:
  # parallel: 2
  failFast: true
  forceExit: true
  language: en
  retry: 0
  strict: true
  verbose: true

  tags: "@prototypes"

  paths:
    - tests/features/**/*.feature

  import:
    - src/tests/support/**/*.js
    - src/tests/steps/**/*.js

  format:
    - "@cucumber/pretty-formatter"

  formatOptions:
    colorsEnabled: true
