default:
  # parallel: 2
  failFast: true
  forceExit: true
  language: en
  retry: 0
  strict: true
  verbose: true

  # Optional for filtering scenarios by tags
  # Keep in mind, tags act as query operators not as combinators
  # tags: "@... and not @... or @..."

  paths:
    - tests/features/**/*.feature

  import:
    - src/tests/support/**/*.js
    - src/tests/steps/**/*.js

  format:
    - "@cucumber/pretty-formatter"

  formatOptions:
    colorsEnabled: true
