default:
  # parallel: 2
  verbose: true
  paths:
    - tests/features/**/*.feature
  import:
    - tests/support/world.js
    - tests/support/hooks.js
    - tests/steps/**/*.js
  format:
    - "@cucumber/pretty-formatter"
  formatOptions:
    colorsEnabled: true
