default:
  # parallel: 2
  failFast: true
  forceExit: true
  language: en
  retry: 0
  strict: true
  verbose: true

  name:
    # - Converting strings to different cases
    # - Converting nested object keys to different cases
    # - Accessing array elements
    # - Accessing array elements with arguments
    # - Resolving different types of path specifiers
    - Checking if a input is of a specific type
    # - Checking if an input is empty

  paths:
    - tests/features/**/*.feature

  import:
    - tests/support/**/*.js
    - tests/steps/**/*.js

  format:
    - "@cucumber/pretty-formatter"

  formatOptions:
    colorsEnabled: true
