library:
  entrypoints:
    - library/**/*.coffee
  outdir: src/library

runtime:
  entrypoints:
    - runtime/**/*.coffee
  outdir: src/runtime

tests:
  entrypoints:
    - tests/**/*.coffee
  outdir: src/tests
