default: &default
  bundle: false
  charset: utf8
  format: esm
  minify: true
  platform: browser
  sourcemap: inline
  target:
    - es2020

library:
  <<: *default

  entryPoints:
    - library/**/*.coffee
  outdir: src/library

registry:
  <<: *default

  entryPoints:
    - runtime/registry.coffee
  outdir: src/registry.js
  platform: node
  target:
    - node20

tests:
  <<: *default

  entryPoints:
    - tests/**/*.coffee
  outdir: src/tests
