server:
  hostname: localhost
  ip: 0.0.0.0
  port: 1234

globs:
  assets:
    src: assets/**/*
    dest: tmp/public

  clean: tmp/**/*

  content:
    src: content/**/*.md
    dest: tmp/content

  locales:
    src: locales/*.yml
    dest: tmp/locales

  manifest:
    src: images/favicon.svg
    dest: tmp/public/manifest

  scripts:
    src: scripts/*.{coffee,js,cjs,mjs}
    dest: tmp/public/js

  styles:
    src: styles/*.{css,styl}
    dest: tmp/public/css

  templates:
    src: tmp/content/**/*.yml
    dest: tmp/public
