server:
  hostname: localhost
  ip: 0.0.0.0
  path: /
  port: 1234

globs:
  clean: tmp/**/*
  locales: locales/**/*.yml
  logs: tmp/logs
  public: tmp/public

  assets:
    src: assets/**/*
    dest: tmp/public

  content:
    src: content/**/*.md
    dest: tmp/content

  manifest:
    src: images/favicon.svg
    dest: tmp/public/manifest

  scripts:
    outputFile: site.js
    src: scripts/*.{coffee,js,cjs,mjs}
    dest: tmp/public/assets/scripts

  styles:
    includes:
      - node_modules
      - styles
      - assets
    src: styles/site.styl
    dest: tmp/public/assets/styles

  templates:
    content: tmp/content/**/*.yml
    src: templates
    dest: tmp/public

# content_routes:
#   "/:path":
#     layout: "default"
#     permalink: /:path
