server:
  hostname: localhost
  ip: 0.0.0.0
  port: 1234

globs:
  clean: tmp/**/*
  locales: locales/**/*.yml
  logs: tmp/logs
  public: tmp/public

  assets:
    src: assets/**/*
    dest: tmp/public

  content:
    src: content/**/*.md
    dest: tmp/content

  manifest:
    src: images/favicon.svg
    dest: tmp/public/manifest

  scripts:
    src: scripts/*.{coffee,js,cjs,mjs}
    dest: tmp/public/js

  styles:
    src: styles/*.{css,styl}
    dest: tmp/public/css

  templates:
    src: tmp/content/**/*.yml
    dest: tmp/public
    views: templates

# content_routes:
#   "/:path":
#     layout: "default"
#     permalink: /:path
