processes:
  install:
    namespace: package
    description: "Install dependencies"
    availability:
      restart: "no"
    command: |
      pnpm install --frozen-lockfile
      pnpm link .

  fresh-install:
    namespace: package
    description: "Fresh install dependencies"
    availability:
      restart: "no"
    command: |
      rm -frv node_modules pnpm-lock.yaml tmp logs
      # pnpm store prune
      pnpm prune
      pnpm install
      pnpm link .

  update:
    namespace: package
    description: "Update dependencies"
    availability:
      restart: "no"
    command: |
      # pnpm upgrade --latest
      # pnpm update --lockfile-only
      pnpm update

  upgrade:
    namespace: package
    description: "Upgrade dependencies"
    availability:
      restart: "no"
    command: |
      corepack up && pnpm add -g pnpm

  outdated:
    namespace: package
    description: "Check for outdated dependencies"
    availability:
      restart: "no"
    command: |
      pnpm outdated
