name: Build and Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PLATE_ENV: github-actions
      PLATE_PKG_PATH: ${{ github.workspace }}
      PLATE_PRJ_PATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Taskfile
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Plate Cli
        run: task -t ./tasks dev:build-cli

      - name: Build project
        run: node ./bin/plate.js dev:build

      - name: Run tests
        run: node ./bin/plate.js dev:test
